title: Git Pages 101
author: MistaPetroz
email: mistapetroz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The description should fill the entire page.

# social links
twitter_username: mistapetroz
github_username:  mistapetroz

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
